[package]
name = "json-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kiv-json-server"
path = "src/main.rs"

[dependencies]
axum = "0.6.18"
core = { path = "../core" }
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.96"
tokio = { version = "1.28.2", features = ["full"] }
kivql = { path = "../kivql" }
clap = { version = "4.3.4", features = ["derive"] }